# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter oneplus7 oneplus7pro oneplus7t oneplus7tpro,$(TARGET_DEVICE)),)

endif
